<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.0" />
    <PackageReference Include="Avalonia.Headless" Version="11.2.0" />
    <PackageReference Include="Avalonia.Skia" Version="11.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../samples/DemoApp/DemoApp.csproj" />
  </ItemGroup>

</Project>
